if (WIN32)
	add_definitions(/EHsc /arch:SSE2 -D_CRT_SECURE_NO_WARNINGS)
endif()

if (EMSCRIPTEN)
	add_definitions(-emit-llvm)
	SET(CMAKE_LINK_LIBRARY_SUFFIX "")

	SET(CMAKE_STATIC_LIBRARY_PREFIX "")
	SET(CMAKE_STATIC_LIBRARY_SUFFIX ".bc")
	SET(CMAKE_SHARED_LIBRARY_PREFIX "")
	SET(CMAKE_SHARED_LIBRARY_SUFFIX ".bc")
	SET(CMAKE_EXECUTABLE_SUFFIX ".html")
	SET(CMAKE_DL_LIBS "" )

	SET(CMAKE_FIND_LIBRARY_PREFIXES "")
	SET(CMAKE_FIND_LIBRARY_SUFFIXES ".bc")
endif()
