echo Cleaning old documentation build directory.
del /Q /S build
del /Q /S xml
mkdir build
mkdir xml

echo Doxygen Version:
doxygen --version

echo Running Doxygen:
doxygen doxyfile

echo Deploying static doc content.
xcopy /s static\*.* build\

echo Generating documentation.
DocGenerator docstructure.xml .\xml .\build\ ..\benchmarks\results > build\reference.html

::TODO: This file is automatically generated, but override it now for manual modifications.
::Remove this line once DocGenerator is improved to support style configurations.
copy static\reference.html build\reference.html
