echo Cleaning old documentation build directory.
del /Q /S build > NUL 2> NUL
del /Q /S xml > NUL 2> NUL
mkdir build > NUL 2> NUL
mkdir xml > NUL 2> NUL

echo Doxygen Version:
doxygen --version

echo Running Doxygen:
doxygen doxyfile

echo Deploying static doc content.
xcopy /s static\*.* build\ > NUL

echo Generating documentation.
DocGenerator docstructure.xml .\xml .\build\ ..\benchmarks\results > build\reference.html

::TODO: This file is automatically generated, but override it now for manual modifications.
::Remove this line once DocGenerator is improved to support style configurations.
copy static\reference.html build\reference.html

::Generate version identifier string to the docs.
set currentdate=%date:~10,4%-%date:~7,2%-%date:~4,2%
echo ^<b^>Documentation Build %currentdate%-git-nightly^</b^> > build\version.html

pause
